version: '3.1'

services:
    backend:
      build: ./backend
      environment:
        - PORT=5000
      restart: unless-stopped
      # networks:
      #   - web-network
      ports:
       - "5000:5000"


    frontend:
      build: ./frontend
      environment:
        - PORT=8000
      # networks:
      #   - web-network
      ports:
       - "8000:8000"

# networks:
#   web-network:
#     driver: bridge